// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAl43yDGOb3VLlBca0KNNNjqKldELHKBSE',
    appId: '1:214527805101:web:77bbc96a7fca67b4366824',
    messagingSenderId: '214527805101',
    projectId: 'ctse-sunday',
    authDomain: 'ctse-sunday.firebaseapp.com',
    storageBucket: 'ctse-sunday.appspot.com',
    measurementId: 'G-5VPPEYBVVR',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBSKz3mYAImRackbCQL2gNPtcUZoukDUAs',
    appId: '1:214527805101:android:ab57a3ed3b16b862366824',
    messagingSenderId: '214527805101',
    projectId: 'ctse-sunday',
    storageBucket: 'ctse-sunday.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCMECpgfsGTWCcXLuUugtqbMMuphdCloTg',
    appId: '1:214527805101:ios:a96f4e8e49bdc305366824',
    messagingSenderId: '214527805101',
    projectId: 'ctse-sunday',
    storageBucket: 'ctse-sunday.appspot.com',
    iosClientId: '214527805101-upamu9v339hs9tg4mim4m7i7st2tf8rh.apps.googleusercontent.com',
    iosBundleId: 'com.example.labActivitySunday',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCMECpgfsGTWCcXLuUugtqbMMuphdCloTg',
    appId: '1:214527805101:ios:a96f4e8e49bdc305366824',
    messagingSenderId: '214527805101',
    projectId: 'ctse-sunday',
    storageBucket: 'ctse-sunday.appspot.com',
    iosClientId: '214527805101-upamu9v339hs9tg4mim4m7i7st2tf8rh.apps.googleusercontent.com',
    iosBundleId: 'com.example.labActivitySunday',
  );
}
